### PR TITLE
Updated due date notifications sent to users

### PR DESCRIPTION
**Pull request by jedrzej**

### CODE REVIEW

**Comment by jedrzej** [comment]
Please don't merge it yet

**Comment by jedrzej** [comment]
Ok, it's ready

**Comment by jkbdbrnwsk** [comment]
@theanxy @karolsojko could we get this one up and running when you gents have a moment?

**Comment by karolsojko** [comment]
looks good to me. How about you @theanxy ?

**Comment by jkbdbrnwsk** [comment]
@theanxy - can we merge this one? :) Cheers!

**Comment by theanxy** [comment]
Nice job Jedrzej. LGTM!

**Pull request merged**
